baseURL = 'https://www.staldal.nu/tech/'
languageCode = 'en'
title = "Mikael Ståldal's technical blog"
description = 'Programming and software'
theme = 'ananke'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = 'category'
